export const FETCHING_MAZES = 'FETCHING_MAZES';
export const FETCHING_MAZE = 'FETCHING_MAZE';
export const FETCHED_MAZES = 'FETCHED_MAZES';
export const FETCHED_MAZE = 'FETCHED_MAZE';
export const FETCHED_MAZE_ERROR = 'FETCHED_MAZE_ERROR';
export const ADDING_MAZE = 'ADDING_MAZE';
export const ADDED_MAZE = 'ADDED_MAZE';
export const ADDING_MAZE_ERROR = 'ADDING_MAZE_ERROR';